[package]
name = "server-manager-rust"
version = "0.1.0"
authors = ["Simen <simen.s.russnes@gmail.com>"]

[dependencies]
actix = "0.7"
actix-web = "0.7"

futures = "0.1"
env_logger = "0.5"
lazy_static = "1.1.0"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
json = "*"
